# Generated by Django 4.0.2 on 2022-04-18 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_alter_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
    ]
