# Generated by Django 4.0.2 on 2022-04-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Message',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
