# Generated by Django 4.0.2 on 2022-04-12 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('cid', models.IntegerField()),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('Description', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='food_images')),
            ],
            options={
                'db_table': 'a_food',
            },
        ),
        migrations.CreateModel(
            name='removefood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_food.category')),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_food.food')),
            ],
            options={
                'db_table': 'removefood',
            },
        ),
    ]
