# Generated by Django 4.0.2 on 2022-03-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tablebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('People', models.IntegerField()),
                ('Message', models.TextField()),
            ],
            options={
                'db_table': 'tablebook',
            },
        ),
        migrations.RemoveField(
            model_name='food',
            name='fid',
        ),
    ]
