# Generated by Django 4.0.2 on 2022-04-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_food', '0003_category_contactus_removefood'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactus',
        ),
        migrations.DeleteModel(
            name='tablebook',
        ),
        migrations.AlterField(
            model_name='food',
            name='Description',
            field=models.CharField(max_length=300),
        ),
    ]
